/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppControlRouteImport } from './routes/app-control'
import { Route as CronsRouteImport } from './routes/crons'
import { Route as DeviceInfoRouteImport } from './routes/device-info'
import { Route as MessageRouteImport } from './routes/message'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShellRouteImport } from './routes/shell'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/app-control',
  path: '/app-control',
  getParentRoute: () => rootRouteImport,
} as any)
const CronsRoute = CronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceInfoRoute = DeviceInfoRouteImport.update({
  id: '/device-info',
  path: '/device-info',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/shell',
  path: '/shell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app-control': typeof AppControlRoute
  '/crons': typeof CronsRoute
  '/device-info': typeof DeviceInfoRoute
  '/message': typeof MessageRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/shell': typeof ShellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-control': typeof AppControlRoute
  '/crons': typeof CronsRoute
  '/device-info': typeof DeviceInfoRoute
  '/message': typeof MessageRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/shell': typeof ShellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app-control': typeof AppControlRoute
  '/crons': typeof CronsRoute
  '/device-info': typeof DeviceInfoRoute
  '/message': typeof MessageRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/shell': typeof ShellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-control'
    | '/crons'
    | '/device-info'
    | '/message'
    | '/notifications'
    | '/settings'
    | '/shell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-control'
    | '/crons'
    | '/device-info'
    | '/message'
    | '/notifications'
    | '/settings'
    | '/shell'
  id:
    | '__root__'
    | '/'
    | '/app-control'
    | '/crons'
    | '/device-info'
    | '/message'
    | '/notifications'
    | '/settings'
    | '/shell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppControlRoute: typeof AppControlRoute
  CronsRoute: typeof CronsRoute
  DeviceInfoRoute: typeof DeviceInfoRoute
  MessageRoute: typeof MessageRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  ShellRoute: typeof ShellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-control': {
      id: '/app-control'
      path: '/app-control'
      fullPath: '/app-control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crons': {
      id: '/crons'
      path: '/crons'
      fullPath: '/crons'
      preLoaderRoute: typeof CronsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-info': {
      id: '/device-info'
      path: '/device-info'
      fullPath: '/device-info'
      preLoaderRoute: typeof DeviceInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shell': {
      id: '/shell'
      path: '/shell'
      fullPath: '/shell'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppControlRoute: AppControlRoute,
  CronsRoute: CronsRoute,
  DeviceInfoRoute: DeviceInfoRoute,
  MessageRoute: MessageRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  ShellRoute: ShellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
